apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
name: tax-calculator-pipeline
spec:
description: Pipeline for installing dependencies, running Jasmine tests, and building the Tax Calculator image.

params:
- name: image
type: string
description: Full IBM Cloud Container Registry image name.

workspaces:
- name: source

tasks:
- name: npminstall
taskRef:
name: npminstall
workspaces:
- name: source
workspace: source

```
- name: tests
  runAfter:
    - npminstall
  taskRef:
    name: tests
  workspaces:
    - name: source
      workspace: source

- name: build
  runAfter:
    - tests
  taskRef:
    name: build
  params:
    - name: IMAGE
      value: $(params.image)
  workspaces:
    - name: source
      workspace: source
```
